### ISSUE TITLE
CropByMask node not found

### ISSUE THREAD

**Issue by YuntongZou** [16131zzzzzzzz/EveryoneNobel#4]
Always get the error popped up as: 
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node LayerUtility: CropByMask does not exist.', 'details': "Node ID '#103'", 'extra_info': {}}
Error during image generation: cannot access local variable 'images' where it is not associated with a value

I already checked all the requirements, making sure they've been successfully installed. But i still get the error.

**Comment by 16131zzzzzzzz** [comment]
I need more details about how you use this workflow. Have you installed the missing nodes in ComfyUI?

**Comment by 16131zzzzzzzz** [comment]
Maybe it is the python problem. See the new quickstart step 1.

**Comment by Utter-pulsar** [comment]
I encountered the same issue, and it says:
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because node LayerUtility: CropByMask does not exist.', 'details': "Node ID '#103'", 'extra_info': {}}

I installed ComfyUI and this should be the last step of generating the expected image. Oh, and it also says:
got prompt
!!! Exception during processing !!! ERROR: Could not detect model type of: C:\Users\Utter\Desktop\EveryoneNobel-main\ComfyUI_windows_portable\ComfyUI\models\checkpoints\XL_Nobel_Prizes_style-000005.safetensors

The terminal says:
Traceback (most recent call last):
  File "main_without_openai.py", line 75, in <module>
    main(args.name, args.subject, args.content, args.image_path, args.comfy_server_address)
  File "main_without_openai.py", line 46, in main
    save_previews=True,
  File "C:\Users\Utter\Desktop\EveryoneNobel-main\src\server.py", line 87, in prompt_image_to_image
    prompt, output_path, input_path, filename, comfy_server_address, save_previews
  File "C:\Users\Utter\Desktop\EveryoneNobel-main\src\server.py", line 104, in generate_image_by_prompt_and_image
    return os.path.join(output_path, images[-1]["file_name"])
UnboundLocalError: local variable 'images' referenced before assignment

**Comment by 16131zzzzzzzz** [comment]
It seems that the issue might be due to incorrect model paths in the JSON file. You will need to modify all the model paths to point to your local directories.

Another solution is to run ComfyUI locally in your browser. Once it’s running, go to the settings and enable the "Dev Mode Options." You can export the workflow in API format as a JSON file. Use this exported JSON to replace the original resources/workflow/nobel_workflow.json.
